# Generated by Django 2.2 on 2020-12-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_auto_20201211_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('last_modiefied', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
